version: 3.9;

services: 
  database:
    image: mongo:5.0-focal
    restart: always
    hostname: ledocker
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports: 
      - "${EXTERNAL_DB}:${INTERNAL_DB}"
  web-server:
    build:
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNSTRING=mongodb://${DB_USER}:${DB_PASS}@ledocker:${INTERNAL_DB}
      - DBNAME=${DBNAME}
      - SESSION_SECRET=${SESSION_SECRET}
      - ITERATIONS=${ITERATIONS}
      - KEYLEN=${KEYLEN}
      - DIGEST=${DIGEST}
    depends_on:
      - database
    ports:
      - "${EXTERNAL_APP}:${INTERNAL_APP}"

