name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1
     - run: |
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker compose -f docker-compose-local.yml build 


