name: docker-compose-local UP

env:
  DB_USER: 123
  DB_PASS: 123
  INTERNAL_DB: 27017
  EXTERNAL_DB: 27017
  INTERNAL_APP: 8080
  EXTERNAL_APP: 80
  DBNAME: "test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1
     - run: |
        npm install wait-on
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker compose -f docker-compose-local.yml up --force-recreate --build -d
        npx wait-on http://localhost:81 -t 10000


